# Generated by Django 3.1.2 on 2020-10-31 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_projeto', models.CharField(max_length=200)),
                ('data_inicio', models.DateTimeField(verbose_name='date published')),
                ('data_fim', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Atividades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_atividade', models.CharField(max_length=200)),
                ('data_inicio', models.DateTimeField(verbose_name='date published')),
                ('data_fim', models.DateTimeField(verbose_name='date published')),
                ('finalizada', models.BooleanField()),
                ('id_projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetos.projetos')),
            ],
        ),
    ]
